import { Membre, Cotisation } from './types';

export const MOIS = [
  'JANVIER', 'FÉVRIER', 'MARS', 'AVRIL', 'MAI', 'JUIN',
  'JUILLET', 'AOÛT', 'SEPTEMBRE', 'OCTOBRE', 'NOVEMBRE', 'DÉCEMBRE'
];

export const initialMembres: Membre[] = [
  {id:'1',prenom:'SOKHNA MAME DIARRA MBACKÉ',nom:'DIENG'},
  {id:'2',prenom:'SERIGNE CHEIKH TIDIANE',nom:'CISSE'},
  {id:'3',prenom:'SOKHNA AMINATA',nom:'CISSE'},
  {id:'4',prenom:'SOKHNA MANAR',nom:'SAMB'},
  {id:'5',prenom:'MOUHAMADOU FALLILOU',nom:'SEYE'},
  {id:'6',prenom:'SERIGNE ISSA',nom:'POUYE'},
  {id:'7',prenom:'SOKHNA FATIM',nom:'KA'},
  {id:'8',prenom:'SOKHNA YAYE KHADY',nom:'DIOP'},
  {id:'9',prenom:'SOKHNA KHOUDIA',nom:'DIENG'},
  {id:'10',prenom:'SERIGNE ADRAMÉ',nom:'FALL'},
  {id:'11',prenom:'SOKHNA ASSIÉTOU',nom:'MBACKÉ'},
  {id:'12',prenom:'SERIGNE NDONGO',nom:'DIOP'},
  {id:'13',prenom:'SOKHNA ADJI GASS',nom:'DIAKHATÉ'},
  {id:'14',prenom:'SERIGNE PAPE DEMBA',nom:'SOW'},
  {id:'15',prenom:'SERIGNE MOUHAMED',nom:'FAYE'},
  {id:'16',prenom:'SERIGNE FALLOU',nom:'FAYE'},
  {id:'17',prenom:'SOKHNA NDÈYE SOKHNA',nom:'DIOP'},
  {id:'18',prenom:'SERIGNE CHEIKH MOURTADA',nom:'KHOLLE'},
  {id:'19',prenom:'SOKHNA AWA',nom:'SENGHOR'},
  {id:'20',prenom:'SOKHNA RAMA',nom:'SYLLA'},
  {id:'21',prenom:'SERIGNE DAOUDA',nom:'DIAGNE'},
  {id:'22',prenom:'SOKHNA ADAMA',nom:'DIOUF'},
  {id:'23',prenom:'SOKHNA ASTOU',nom:'BÈYE'},
  {id:'24',prenom:'SOKHNA AMY',nom:'FAYE'},
  {id:'25',prenom:'SOKHNA ABSA',nom:'DIOP'},
  {id:'26',prenom:'SOKHNA FATIMA',nom:'DIOP'},
  {id:'27',prenom:'SERIGNE DAME',nom:'NDIAYE'},
  {id:'28',prenom:'CHEIKH AHMADOU BAMBA',nom:'DIENG'},
  {id:'29',prenom:'SOKHNA RAMATOULAYE',nom:'FALL'},
  {id:'30',prenom:'SOKHNA DABA',nom:'SÈNE'},
  {id:'31',prenom:'CHEIKH AHMADOU BAMBA',nom:'DIENG FRA'},
  {id:'32',prenom:'SOKHNA KHADIJA NDOYE',nom:'BA'},
  {id:'33',prenom:'SERIGNE PAPE MBAYE',nom:'SECK'},
  {id:'34',prenom:'SOKHNA AWA',nom:'SENE'},
  {id:'35',prenom:'SERIGNE CHEIKH',nom:'LEYE'},
  {id:'36',prenom:'CHEIKH ABDOULAHI DIAKHATE',nom:'GUEYE'},
  {id:'37',prenom:'SOKHNA AMSATOU',nom:'NDIAYE'},
  {id:'38',prenom:'SERIGNE MOUSTAPHA',nom:'SECK'},
  {id:'39',prenom:'SOKHNA FATY',nom:'BABOU'},
  {id:'40',prenom:'SOKHNA',nom:'DIOUF'},
  {id:'41',prenom:'SOKHNA FATOU KINÉ',nom:'POUYE'},
  {id:'42',prenom:'SOKHNA FATOU DIOP',nom:'NDIAYE'},
  {id:'43',prenom:'SERIGNE MOUHAMED DJIDIACK',nom:'FAYE'},
  {id:'44',prenom:'SERIGNE MOURTADA',nom:'MBAYE'},
  {id:'45',prenom:'SERIGNE MOUHAMED',nom:'SAMB'},
  {id:'46',prenom:'SERIGNE BASSIROU',nom:'KANE'},
  {id:'47',prenom:'SERIGNE MOUHAMADOU FADILOU',nom:'FALL'},
  {id:'48',prenom:'SERIGNE MOUNTAKHA',nom:'NDIONGUE'},
  {id:'49',prenom:'SERIGNE KHADIM MBACKE',nom:'NIANG'},
  {id:'50',prenom:'SERIGNE KHADIM',nom:'FAYE'},
  {id:'51',prenom:'SERIGNE MATAR',nom:'DIA'},
  {id:'52',prenom:'SOKHNA MBACKE',nom:'DIATTARA'},
  {id:'53',prenom:'SOKHNA MAME DIARRA',nom:'MBACKÉ'},
  {id:'54',prenom:'SOKHNA TAHIRATOU',nom:'KA'},
  {id:'55',prenom:'SOKHNA KHADIJA',nom:'DIA'},
  {id:'56',prenom:'SERIGNE FALILOU',nom:'NIANE'},
  {id:'57',prenom:'SOKHNA ANNA',nom:'SOW'},
  {id:'58',prenom:'SOKHNA MAME DIARRA MBACKÉ',nom:'DIENG'},
];

export const initialCotisations: Cotisation[] = [
  {id:'1',mId:'1',mois:'JANVIER',annee:2025,montant:500,mode:'WAVE'},
  {id:'2',mId:'3',mois:'JANVIER',annee:2025,montant:500,mode:'WAVE'},
  {id:'3',mId:'5',mois:'JANVIER',annee:2025,montant:500,mode:'WAVE'},
  {id:'4',mId:'7',mois:'JANVIER',annee:2025,montant:500,mode:'WAVE'},
  {id:'5',mId:'9',mois:'JANVIER',annee:2025,montant:500,mode:'WAVE'},
  {id:'6',mId:'1',mois:'FÉVRIER',annee:2025,montant:500,mode:'OM'},
  {id:'7',mId:'2',mois:'FÉVRIER',annee:2025,montant:0,mode:'OM'},
  {id:'8',mId:'3',mois:'FÉVRIER',annee:2025,montant:500,mode:'OM'},
  {id:'9',mId:'4',mois:'FÉVRIER',annee:2025,montant:0,mode:'WAVE'},
  {id:'10',mId:'5',mois:'FÉVRIER',annee:2025,montant:500,mode:'WAVE'},
  {id:'11',mId:'6',mois:'FÉVRIER',annee:2025,montant:0,mode:'WAVE'},
  {id:'12',mId:'7',mois:'FÉVRIER',annee:2025,montant:500,mode:'WAVE'},
  {id:'13',mId:'8',mois:'FÉVRIER',annee:2025,montant:0,mode:'OM'},
  {id:'14',mId:'9',mois:'FÉVRIER',annee:2025,montant:500,mode:'OM'},
  {id:'15',mId:'1',mois:'MARS',annee:2025,montant:500,mode:'WAVE'},
  {id:'16',mId:'2',mois:'MARS',annee:2025,montant:0,mode:'OM'},
  {id:'17',mId:'3',mois:'MARS',annee:2025,montant:500,mode:'OM'},
  {id:'18',mId:'4',mois:'MARS',annee:2025,montant:0,mode:'WAVE'},
  {id:'19',mId:'5',mois:'MARS',annee:2025,montant:500,mode:'WAVE'},
  {id:'20',mId:'6',mois:'MARS',annee:2025,montant:0,mode:'WAVE'},
  {id:'21',mId:'7',mois:'MARS',annee:2025,montant:500,mode:'WAVE'},
  {id:'22',mId:'8',mois:'MARS',annee:2025,montant:0,mode:'WAVE'},
  {id:'23',mId:'9',mois:'MARS',annee:2025,montant:500,mode:'WAVE'},
  {id:'24',mId:'1',mois:'AVRIL',annee:2025,montant:600,mode:'WAVE'},
  {id:'25',mId:'5',mois:'AVRIL',annee:2025,montant:800,mode:'WAVE'},
  {id:'26',mId:'6',mois:'AVRIL',annee:2025,montant:0,mode:'OM'},
  {id:'27',mId:'7',mois:'AVRIL',annee:2025,montant:500,mode:'WAVE'},
  {id:'28',mId:'9',mois:'AVRIL',annee:2025,montant:500,mode:'WAVE'},
];

export const initialDepenses: import('./types').Depense[] = [
  { id: '1', evenement: 'Achat de fournitures', montant: 1500, mois: 'JANVIER', annee: 2025, date: '2025-01-15' },
  { id: '2', evenement: 'Transport', montant: 500, mois: 'FÉVRIER', annee: 2025, date: '2025-02-10' },
];
